# Generated by Django 3.2.6 on 2021-09-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_alter_image_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='face_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_access', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
