# Generated by Django 3.2.6 on 2021-09-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_face_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='face_image',
            name='message',
            field=models.CharField(default='hello', max_length=1000),
        ),
    ]
