# Generated by Django 3.2.6 on 2021-09-28 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_face_image_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face_image',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.image'),
        ),
    ]
