# Generated by Django 3.2.6 on 2021-10-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_alter_face_image_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='twitter_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('API_key', models.CharField(max_length=500)),
                ('API_Secrete_key', models.CharField(max_length=500)),
                ('Access_token', models.CharField(max_length=500)),
                ('Access_token_secrete', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='')),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='face_image',
        ),
    ]
